### ISSUE TITLE
Cannot import name 'check_random_state' from 'tensorly.random'

### ISSUE THREAD

**Issue by cloudy-sfu** [huawei-noah/BHT-ARIMA#6]
When running `main.py`, Python reports: 
Cannot import name 'check_random_state' from 'tensorly.random'

Suggestion: Replace the following line with

```
import tensorly.random
```

https://github.com/huawei-noah/BHT-ARIMA/blob/d88c7cedaa9c60b317d501eb595ec6f6ee72dced/BHT_ARIMA/util/functions.py#L18

**Comment by YREC710** [comment]
replace
#from tensorly.random import check_random_state
import tensorly.random
